# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: VUE.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  buildAndTest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install --global yarn
    - run: yarn install 
    - run: yarn run build 
    - run: ls 
    - run: ls dist/
    - run: pwd dist
    
#     - name: 'Testing '
#       run : echo 'testing'.
#      - run : npm run test

    - name: 'Task 1: Connect to AWS '
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: 'Task 2: Upload  to S3 bucket'
      run: aws s3 cp /home/runner/work/vuejs-sonar/vuejs-sonar/dist s3://githubaction-vuejs --recursive
